<form id="co-marketing2-form" action="">
<fieldset>
    <ul class="form-list">
    <li id="marketing2-form">
        <fieldset>
            <ul>
                <li class="wide">
                    <label for="marketing2:like" class="required"><em>*</em><?php echo $this->__('Do you like this post?') ?></label>
                    <div class="input-box">
                        <input type='text' name='marketing2[like]'  class="required-entry input-text" id="marketing2:like" value='<?php echo $this->getQuote()->getMarketingLike2()?>'/>
                    </div>
                </li>
            </ul>
        </fieldset>
     </li>
    </ul>
    <div class="buttons-set" id="marketing2-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="marketing2.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="marketing2-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var marketing = new MarketingMethod2('co-marketing2-form','<?php echo $this->getUrl('mktgmodule/onepage/saveMarketing2') ?>');
    var marketingForm2 = new VarienForm('co-marketing2-form');
//]]>
</script>
